name: Generate Doxygen Docs

on:
  push:
    branches:
      - docs-ci
  workflow_dispatch:

jobs:
  doxygen:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install Doxygen
        run: |
          sudo apt update
          sudo apt install -y doxygen graphviz

      - name: Build Documentation
        run: |
          doxygen Doxyfile

      - name: Upload docs artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./html   # ця папка має відповідати HTML_OUTPUT у Doxyfile

  deploy:
    needs: doxygen
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write

    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
